# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/PageAnalyse_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageAnalyse(object):
    def setupUi(self, PageAnalyse):
        PageAnalyse.setObjectName("PageAnalyse")
        PageAnalyse.resize(400, 435)

        self.retranslateUi(PageAnalyse)
        QtCore.QMetaObject.connectSlotsByName(PageAnalyse)

    def retranslateUi(self, PageAnalyse):
        _translate = QtCore.QCoreApplication.translate
        PageAnalyse.setWindowTitle(_translate("PageAnalyse", "PageAnalyse"))
